QuestApplication/Entities/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QuestApplication.Entities
{
    public class Question
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        [Display(Name = "Question :")]
        public string Description { get; set; }

        public int SerialNo { get; set; }

        public string OptionOne { get; set; }

        public string OptionTwo { get; set; }
        public string OptionThree { get; set; }
        public string OptionFour { get; set; }

        public string Answer { get; set; }

        public int Mark { get; set; }

        public virtual Assignment Assignment { get; set; }
    }
}

QuestApplication/Controllers/AssignmentController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using QuestApplication.Entities;
using QuestApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuestApplication.Controllers
{
    [Authorize]
    public class AssignmentController : Controller
    {
        ApplicationDbContext context;

        public AssignmentController()
        {
            context = new ApplicationDbContext();            
        }

        #region Assignment        

        public void IsTeacherUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                ViewBag.IsTeacher = s[0].ToString() == "Teacher";
            }            
        }

        // GET: Assignment
        public ActionResult Index()
        {
            IsTeacherUser();
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;                                               
            }
            else            
                ViewBag.Name = "Not Logged IN";            

            return View(context.Assignments);
        }

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        public ActionResult Create(int? id)
        {
            var assignment = context.Assignments.FirstOrDefault(c => c.Id == id);
            assignment = assignment ?? new Assignment();
            return View(assignment);
        }

        [Authorize(Roles = "Teacher")]
        [HttpPost]
        public ActionResult Create(Assignment assignment)
        {
            if (!ModelState.IsValid)
                return View(assignment);

            if (assignment.Id > 0)
            {
                var dbAssign = context.Assignments.FirstOrDefault(c => c.Id == assignment.Id);
                if(dbAssign!=null)
                {
                    dbAssign.Name = assignment.Name;
                    dbAssign.MaxTime = assignment.MaxTime;
                }
            }
            else
                context.Assignments.Add(assignment);

            context.SaveChanges();
            TempData["AssignmentId"] = assignment.Id;
            return RedirectToAction("Details");                        
        }

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if(!id.HasValue)
                id = Convert.ToInt32(TempData["AssignmentId"]);
            
            IsTeacherUser();
            var assignment = context.Assignments.FirstOrDefault(c=>c.Id == id);
            assignment = assignment ?? new Assignment();
            assignment.Questions = context.Questions.Where(c => c.Assignment.Id == assignment.Id).ToList();
            TempData["AssignmentId"] = assignment.Id;
            return View("Details", assignment);
        }

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var assignment = context.Assignments.FirstOrDefault(c => c.Id == id);
            if(assignment!=null)
            {
                context.Assignments.Remove(assignment);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        #endregion

        #region Question

        [Authorize(Roles = "Teacher")]
        [HttpGet]
        public ActionResult CreateQuestion(int? questionId)
        {
            var question = context.Questions.FirstOrDefault(c => c.Id == questionId);
            question = question ?? new Question();
            return View(question);
        }

        [Authorize(Roles = "Teacher")]
        [HttpPost]
        public ActionResult CreateQuestion(Question question)
        {
            if (ModelState.IsValid)
            {
                if (question.Id > 0)
                {
                    var questionEntity = context.Questions.FirstOrDefault(c => c.Id == question.Id);
                    if (questionEntity != null)
                    {
                        MapQuestionPropertiesToDatabase(questionEntity, question);         
                    }
                }
                else
                {
                    question.Assignment = GetAssignment();
                    context.Questions.Add(question);
                }
                context.SaveChanges();
            }
           
            return RedirectToAction("Details");
        }



        //[Authorize(Roles = "Student")]
        //public ActionResult Question(int? id)
        //{
        //    var asssignment = context.Assignments.FirstOrDefault(c => c.Id == id);
        //    if (asssignment != null)
        //    {
        //        asssignment.Questions = context.Questions.Where(c => c.Assignment.Id == id).ToList();
        //        var question = asssignment.Questions.Last();

        //        return View(question);
        //    }
        //    return RedirectToAction("Index");
        //}

        //[Authorize(Roles = "Student")]
        //[HttpPost]
        //public ActionResult Question(Question question)
        //{
        //    //var optionFour = collection["OptionFour"];
        //    //var id = collection["Id"];
        //    return RedirectToAction("Index");
        //}

        private void MapQuestionPropertiesToDatabase(Question questionEntity, Question question)
        {
            questionEntity.Mark = question.Mark;
            questionEntity.Description = question.Description;
            questionEntity.OptionOne = question.OptionOne;
            questionEntity.OptionTwo = question.OptionTwo;
            questionEntity.OptionThree = question.OptionThree;
            questionEntity.Answer = question.Answer;

        }

        private Assignment GetAssignment()
        {
            var assessmentId = Convert.ToInt32(TempData["AssignmentId"]);
            var assignment = context.Assignments.FirstOrDefault(c => c.Id == assessmentId);
            return assignment;
        }

        

        [Authorize(Roles = "Teacher")]
        public ActionResult DeleteQuestion(int? questionId)
        {
            var question = context.Questions.FirstOrDefault(c => c.Id == questionId);
            if(question!=null)
            {
                context.Questions.Remove(question);
                context.SaveChanges();
            }
            return RedirectToAction("Details");
        }

        #endregion
    }
}

QuestApplication/Controllers/QuestionController.cs
using QuestApplication.Entities;
using QuestApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuestApplication.Controllers
{
    public class QuestionController : Controller
    {
        ApplicationDbContext context;
        static List<Question> questions;
        static int marks;

        public QuestionController()
        {
            ViewBag.Answer = null;
            context = new ApplicationDbContext();
        }
      
        [Authorize(Roles = "Student")]
        [HttpGet]
        public ActionResult Question(int? assessmentId, Question question= null)
        {
            if(question.Id > 0)
            {
                return View(question);
            }
            var asssignment = context.Assignments.FirstOrDefault(c => c.Id == assessmentId);
            if (asssignment != null)
            {
                questions = context.Questions.Where(c => c.Assignment.Id == assessmentId).ToList();
                questions.ForEach(c => c.SerialNo = questions.IndexOf(c) + 1);
                return View(questions.FirstOrDefault());
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Student")]
        [HttpPost]
        public ActionResult Question(Question question)
        {
            if(question.OptionFour == question.Answer)
            {
                ViewBag.Answer = "Correct Answer";
                marks++;
            }
            else
            {
                ViewBag.Answer = "Wrong Answer";
                marks--;
            }
            return View(question);
        }

        [HttpGet]
        public ActionResult NextQuestion(int? serialNo)
        {
            if (serialNo <= questions.Count)
            {
                var question = questions.FirstOrDefault(c => c.SerialNo == serialNo);
                return RedirectToAction("Question", question);
            }
            else
            {                              
                return RedirectToAction("Result");
            }
            
        }

        public ActionResult Result()
        {            
            ViewBag.Remark = "Congratulations. You have scored " + marks + " out of " + questions.Count();
            return View();
        }
    }
}

QuestApplication/Views/Question/Question.cshtml
@model QuestApplication.Entities.Question

@{
    ViewBag.Title = "Question";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Question"))
{
    @Html.AntiForgeryToken()    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Description)
        @Html.HiddenFor(model => model.OptionOne)
        @Html.HiddenFor(model => model.OptionTwo)
        @Html.HiddenFor(model => model.OptionThree)
        @Html.HiddenFor(model => model.Mark)
        @Html.HiddenFor(model => model.Answer)
        @Html.HiddenFor(model => model.SerialNo)
        <fieldset id="QuestionFieldSet">
            @ViewBag.Answer
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.RadioButtonFor(model => model.OptionFour, @Html.DisplayFor(model => model.OptionOne))
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OptionOne)
                </dd>

                <dt>
                    @Html.RadioButtonFor(model => model.OptionFour, @Html.DisplayFor(model => model.OptionTwo))
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OptionTwo)
                </dd>

                <dt>
                    @Html.RadioButtonFor(model => model.OptionFour, @Html.DisplayFor(model => model.OptionThree))
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OptionThree)
                </dd>

            </dl>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </fieldset>        
           
                   
        <p>@ViewBag.Result</p>
    </div>
}    
     
    <div>

        @Html.ActionLink("Next", "NextQuestion", new { @serialNo = Model.SerialNo + 1 }) <br/>
        @Html.ActionLink("Back to Assignment List", "Index", "Assignment")
    </div>

QuestApplication/Views/Question/Result.cshtml
@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Result</h2>
  @ViewBag.Remark
<div>    
    @Html.ActionLink("Back to Assignment List", "Index", "Assignment")
</div>